php-rust-tools/parser

trunk_parser/src/parser/mod.rs
A tiny PR adding support for one-liner if statements. I am very new to Rust so I hope the implementation is correct. All tests ran successfully.
=> parser: support one-liner if statements

phpast/samples/if.php, trunk_parser/src/ast.rs, trunk_parser/src/parser/mod.rs
Added parser support for the `else` branch inside if statements.
```php
<?php
if($foo) {
return $foo;
} else {
return $foo;
}
```
=> parser: support else statements

.github/workflows/tests.yml, trunk_lexer/src/lexer.rs
This project requires nightly Rust due to use of if-let chaining (see https://github.com/rust-lang/rust/issues/53667). It's a nice quality-of-life change that I'm also looking forward to using once it's stable, but I found that requiring nightly presented a small barrier to me when I tried to build and run this project.
The first commit of this PR runs rustfmt on the lexer source, since my editor did it automatically. I hope this is okay, but if there's another format I should use instead I'd be happy to make changes.
=> Remove nightly Rust requirement

trunk_parser/src/ast.rs, trunk_parser/src/parser/mod.rs
PHP allows blocks to be added anywhere in a statement context. eg:
```php
<?php
{}
{
echo "We're inside a block\n";
}
```
=> Add support for block statements

trunk_lexer/src/lexer.rs
This meant a variable named $a1 was treated as two separate tokens: the variable $a, and an integer literal.
=> Fix off-by-one error when lexing variable names

trunk_lexer/src/lexer.rs, trunk_lexer/src/token.rs, trunk_parser/src/ast.rs, trunk_parser/src/parser/mod.rs
This also refactors all for include operations to share a `Statement::Include` variant, with a new `IncludeKind` type, as implementing four separate variants felt like too much repetition.
=> Parse include and include_once

trunk_lexer/src/lexer.rs, trunk_parser/src/parser/mod.rs
=> lexer&parser: better support for close tags

trunk_parser/src/ast.rs, trunk_parser/src/parser/mod.rs
=> parser: support multiple unions and intersections

trunk_lexer/src/lexer.rs, trunk_lexer/src/token.rs, trunk_parser/src/ast.rs, trunk_parser/src/parser/mod.rs
Related to #19.
The support for `@` expressions is limited with these changes and there will likely be precedence problems. Those will need to be fixed at a later date perhaps using the `nikic/php-parser` tests.
=> parser: support for error suppress expressions

trunk_lexer/src/lexer.rs, trunk_parser/src/parser/mod.rs
Closes #48.
The lexer was skipping 1 too many characters when tokenising the code - if the property name was more than 1 character long this would have been more obvious.
Test case added to the parser to ensure it continues working.
=> lexer: fix nullsafe arrow token skipping too many characters

trunk_parser/src/ast.rs, trunk_parser/src/parser/mod.rs
Closes #44.
Also adds missing test coverage for:
* Try with a single catch
* Try with a single catch and no variable binding
* Try with multiple catches
* Try with catch and finally
* Try without catch and finally
=> parser: support catch conditions without variables

trunk_parser/src/parser/mod.rs
Initial work towards #45.
Currently only supports defining a single constant, still needs to support multiple constants in the same statement but that will require larger changes to the `Statement` node since classes share the same one (probably not a good idea, the class should probably use `ClassConstant` instead).
=> parser: support top-level constants

trunk_parser/src/ast.rs, trunk_parser/src/parser/mod.rs
Closes #59.
I was a little hesitant to support this since at runtime, arrays aren't allowed to have empty items (it's just a parser detail), but if PHP-Parser supports it we should too.
=> fix: support empty array items

trunk_parser/src/ast.rs, trunk_parser/src/parser/mod.rs
Closes #45.
Refactored out `Constant` variant and now have a separate one for classes to use (`ClassConstant`).
=> feature: support defining multiple constants in one statement

trunk_parser/src/parser/mod.rs
I was very surprised by this, but you can see it in the [php-parser grammar](https://github.com/nikic/PHP-Parser/blob/master/grammar/php.y#L587-L590) and [test case](https://github.com/nikic/PHP-Parser/blob/master/test/code/parser/stmt/switch.test#L9), and indeed it works if you try against the real language implementation.
=> Switch cases can be terminated with semicolons

trunk_lexer/src/lexer.rs, trunk_parser/src/parser/mod.rs
=> parser: support backed enums with cases that have no backing value

trunk_lexer/src/lexer.rs
This re-works the lexer to use a buffer (`peek_buf` method) for lookahead instead of a single byte. This allows us to use one big pattern match for most things instead of having sub-branches within each case.
There's definitely a chance I've broken something, but all the existing tests pass.
I've also pulled out some of the larger cases into separate methods and factored out common number tokenization logic.
I really want to re-work how the column and line tracking is done but when I tried I ended up going down a rabbit hole, and will look at that as a separate piece.
=> Lexer lookahead refactor

trunk_lexer/src/lexer.rs, trunk_lexer/src/token.rs, trunk_parser/src/ast.rs, trunk_parser/src/parser/mod.rs
Closes #71.
Introduces a new `LexerState::Halted` variant. This will tell the lexer to ensure that the token is followed by `();` same as PHP itself.
It then just collects the rest of the tokens into a single `InlineHtml` token (probably could have done this differently but it works for now) and breaks out of the tokenization loop.
=> parser/lexer: support __halt_compiler token

trunk_parser/src/ast.rs, trunk_parser/src/parser/mod.rs
Related to #69 and #74.
Missed support for `static fn () => null` and added test case for both the basic version and the version that returns a reference.
=> parser: add support for static arrow functions

trunk_parser/src/ast.rs, trunk_parser/src/parser/mod.rs
Closes #73.
I'm making the decision to not keep functionality inline with PHP-Parser in this case - something like `new Foo(...)` just doesn't make sense syntactically or functionally. In these cases, I'm happy to build a better parser.
On the `$this?->foo(...)` front, we don't actually support nullsafe method calls right now. I've opened #84 to cover that.
=> parser: support first class callables on functions

trunk_parser/src/ast.rs, trunk_parser/src/parser/ident.rs, trunk_parser/src/parser/mod.rs
Related to #32.
Have added dedicated `Type` variants for all three since they're special cases. There's also no PHP version specific logic here.
=> parser: support `null`/`true`/`false` as a type

trunk_lexer/src/lexer.rs, trunk_lexer/src/token.rs
This re-works the string lexing and implements all escape sequences. It also now returns an error for unterminated strings.
Fixes #21
=> lexer: implement all string escape sequences

trunk_lexer/src/lexer.rs
Even though this is a pretty obscure feature, it's easy to implement now after recent lexer changes.
Fixed #72
=> lexer: implement binary strings

trunk_lexer/src/lexer.rs, trunk_lexer/src/token.rs, trunk_parser/src/ast.rs, trunk_parser/src/parser/mod.rs
Closes #77.
Introduces a new `Expression::DynamicVariable` variant that will also be used for `$$foo` too.
=> parser/lexer: support braced variables

trunk_parser/src/parser/mod.rs, trunk_parser/src/parser/precedence.rs
After the precedence changes, `new Foo()` was being parsed as `(new (call Foo))` instead of `(new Foo)`.
=> parser: fix new expressions being parsed incorrectly

.github/workflows/tests.yml, trunk_parser/src/parser/mod.rs, trunk_parser/src/parser/params.rs
New `Parser.args_list()` method which returns a `Vec<Arg>>`.
Closes #94.
=> parser: abstract call argument parsing logic

trunk_parser/src/ast.rs, trunk_parser/src/parser/mod.rs
I've gone with a pretty simple AST representation, where there are just two parts to strings: constant and expression.
This does lose some information if we want to support AST-rewriting as a use case, since these all parse to the same thing:
```
"$foo"
"{$foo}"
"${foo}"
```
They do the same thing at runtime, though. (You can come up with similar examples for array indexing and property fetching.)
I'm not sure what the philosophy is here, and whether it's something we want to try to get right now or are happy to put off to later.
Fixes #97. (I'll file another issue to mention the few corner cases I'm aware of.)
=> Parse interpolated strings

trunk_parser/src/parser/mod.rs, trunk_parser/src/parser/precedence.rs
This was missing and meant shorthand ternary didn't parse.
=> Add precedence for shorthand ternary operator

README.md, bin/snapshot.rs, src/lexer/byte_string.rs, src/lexer/mod.rs, src/lexer/source.rs, src/lexer/state.rs, src/main.rs, tests/fixtures/0269/ast.txt, tests/fixtures/0269/code.php, tests/fixtures/0269/tokens.txt, tests/test.rs
Not much of a performance gain, but it makes lexer state easier to work with.
benchmarks:
before:
```
Time (mean ± σ):      2.519 s ±  0.017 s    [User: 2.611 s, System: 0.225 s]
Range (min … max):    2.501 s …  2.551 s    10 runs
```
after:
```
Time (mean ± σ):      2.451 s ±  0.007 s    [User: 2.561 s, System: 0.190 s]
Range (min … max):    2.443 s …  2.462 s    10 runs
```
=> chore: separate source from state

src/lexer/mod.rs, src/lexer/state.rs, src/lexer/token.rs, src/parser/expressions.rs, src/parser/internal/loops.rs, tests/fixtures/0226/lexer-error.txt, tests/fixtures/0226/parser-error.txt, tests/fixtures/0227/lexer-error.txt, tests/fixtures/0227/parser-error.txt, tests/fixtures/0233/lexer-error.txt, tests/fixtures/0233/parser-error.txt, tests/fixtures/0234/lexer-error.txt, tests/fixtures/0234/parser-error.txt
Closes #161.
I'm returning `SyntaxError`s from the parser, but don't really care at this point. Handling the intricacies of heredocs & nowdocs in the parser is SO much easier than carrying state around inside of a `StackFrame` and having to mess with the borrow checker.
I ran the Symfony and Laravel third party tests and there's no sign of heredoc/nowdoc errors so I'm taking that as a win.
I'm more or less praying that it's all correct and that I never have to come back to this, lol. In theory though, this code with the comments is much easier to debug going forward. Debugging errors in the lexer before was impossible, at least now all the heavy lifting is done in the parser.
=> fix: better heredoc/nowdoc implementation

src/parser/error.rs, src/parser/expressions.rs, src/parser/internal/goto.rs, src/parser/internal/identifiers.rs, src/parser/mod.rs, tests/fixtures/0285-reserved-type-name/ast.txt, tests/fixtures/0285-reserved-type-name/code.php, tests/fixtures/0286-reserved-type-name/code.php, tests/fixtures/0286-reserved-type-name/parser-error.txt, tests/fixtures/0287-reserved-label-name/code.php, tests/fixtures/0287-reserved-label-name/parser-error.txt, tests/fixtures/0288-reserved-label-name/code.php, tests/fixtures/0288-reserved-label-name/parser-error.txt
this fixes bunch of cases regarding the usage of reserved keywords as identifiers and label names, also adds a good error message for when a reserved keyword is used for a label.
=> fix: fix usage of reserved keywords as label names, and identifiers

src/parser/error.rs, src/parser/expressions.rs, src/parser/internal/classes.rs, src/parser/internal/enums.rs, src/parser/internal/parameters.rs, src/parser/internal/uses.rs, src/parser/mod.rs, tests/fixtures/0297-enum-serialize/code.php, tests/fixtures/0297-enum-serialize/parser-error.txt, tests/fixtures/0298-enum-unserialize/code.php, tests/fixtures/0298-enum-unserialize/parser-error.txt, tests/fixtures/0299-enum-get/code.php, tests/fixtures/0299-enum-get/parser-error.txt, tests/fixtures/0300-enum-set/code.php, tests/fixtures/0300-enum-set/parser-error.txt, tests/fixtures/0301-enum-call/code.php, tests/fixtures/0301-enum-call/parser-error.txt, tests/fixtures/0302-enum-call-static/code.php, tests/fixtures/0302-enum-call-static/parser-error.txt, tests/fixtures/0303-enum-invoke/code.php, tests/fixtures/0303-enum-invoke/parser-error.txt, tests/fixtures/0304-enum-dtor/code.php, tests/fixtures/0304-enum-dtor/parser-error.txt, tests/fixtures/0305-enum-sleep/code.php, tests/fixtures/0305-enum-sleep/parser-error.txt, tests/fixtures/0306-enum-wakeup/code.php, tests/fixtures/0306-enum-wakeup/parser-error.txt, tests/fixtures/0307-uses-commented/ast.txt, tests/fixtures/0307-uses-commented/code.php, tests/third_party_tests.rs
fixes multiple issues regarding comments not being skipped properly, and errors for magic methods on enums ( ref #205 )
the `use` parser is currently broken, and is only able to handle basic use statements, we would need to refactor it.
=> fix multiple parse errors, and error for magic methods on enums

bin/snapshot.rs, src/main.rs, src/parser/expressions.rs, src/parser/internal/arrays.rs, src/parser/internal/attributes.rs, src/parser/internal/blocks.rs, src/parser/internal/classes.rs, src/parser/internal/constants.rs, src/parser/internal/control_flow.rs, src/parser/internal/data_type.rs, src/parser/internal/enums.rs, src/parser/internal/functions.rs, src/parser/internal/identifiers.rs, src/parser/internal/interfaces.rs, src/parser/internal/loops.rs, src/parser/internal/modifiers.rs, src/parser/internal/namespaces.rs, src/parser/internal/parameters.rs, src/parser/internal/properties.rs, src/parser/internal/traits.rs, src/parser/internal/try_block.rs, src/parser/internal/uses.rs, src/parser/internal/utils.rs, src/parser/internal/variables.rs, src/parser/macros.rs, src/parser/mod.rs, src/parser/state.rs, src/parser/stream.rs, tests/test.rs, tests/third_party_tests.rs
this token stream allows us not to worry about comments, instead just focus on relevant tokens, comments are always collected, in a future PR, i plan to:
1. change `TokenStream::comments()` to return `CommentGroup` node
2. attach `CommentGroup` node to every node, starting with types, functions, ..etc, so that we can support doc blocks.
=> feat: introduce token stream

src/lexer/mod.rs, src/lexer/token.rs, src/parser/ast/mod.rs, src/parser/expressions.rs, src/parser/internal/identifiers.rs, tests/fixtures/0001/ast.txt, tests/fixtures/0215/ast.txt, tests/fixtures/0216/ast.txt, tests/fixtures/0218/ast.txt, tests/fixtures/0219/ast.txt, tests/fixtures/0221/ast.txt
We didn't actually parse these correctly, they would be parsed as identifiers / call expressions depending on usage.
=> parser: support die/exit expressions

src/parser/mod.rs, src/parser/stream.rs
before:
after:
not the best metric to go by, but it shows good improvements :)
=> chore: improve performance for token stream

Cargo.toml, src/main.rs, tests/third_party_tests.rs
This PR:
- Let `clap` handle the command line arguments and options
I'm pretty new with rust, please let me know if I'm doing something wrong, I'm here to learn :)
=> chore: use `clap` to have command line arguments

.gitignore, tests/test.rs, tests/third_party_tests.rs
Hi everyone!
I'm excited to make my first contribution to the project. I recently started learning about parsers and interpreters, and I've been really interested in exploring the subject further. As a beginner in both the subject and Rust, working on this project is definitely a great way to learn.
I noticed that there were some areas of the codebase where the style and formatting could be improved, so I took the time to make some changes.
Are you guys open to accepting this kind of change?
Cheers!
=> chore: aesthetic updates to tests

src/lexer/mod.rs, src/lexer/token.rs, src/parser/ast/mod.rs, src/parser/expressions.rs, src/parser/internal/identifiers.rs, tests/fixtures/0329-compiler-halt-offset/ast.txt, tests/fixtures/0329-compiler-halt-offset/code.php
=> feature: recognise __COMPILER_HALT_OFFSET__ as a magic constant

src/parser/internal/arrays.rs, src/parser/internal/identifiers.rs, tests/fixtures/0101/ast.txt, tests/fixtures/0102/ast.txt, tests/fixtures/0329/ast.txt, tests/fixtures/0329/code.php
=> fix: allow reserved keywords in namespaces

tests/third_party_tests.rs
Hyperf is a coroutine framework that runs on top of Swoole. They have dozens of components that do a variety of tasks.
I know that we only need to select some frameworks, the most used ones. Hyperf is one of them, in my opinion.
This is just a suggestion, if we're fine with the ones we already test, feel free to close this PR.
=> chore: add hyperf to third party tests
