trunk_lexer/src/lexer.rs
trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs

parser: support do/while statements

---

trunk_lexer/src/lexer.rs
trunk_lexer/src/token.rs
trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs

parser: support global statements

---

trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs

Closes #43.
I've not covered the alternative syntax for this statement in this PR since that will come under #20 (I'll handle all of them when that comes around).

parser: support basic declare statements

---

trunk_lexer/src/lexer.rs
trunk_lexer/src/token.rs
trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs

parser: support readonly classes

---

trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs

parser: support readonly class properties

---

trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs

Closes #70.
Never a huge fan of nested if statements but the intent is quite clear here so I'm fine with it for now.

feature: support global braced namespace

---

trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs

parser: support static closures

---

trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs
trunk_parser/src/parser/params.rs

parser: add test cases for foreach refs

---

trunk_lexer/src/lexer.rs
trunk_lexer/src/token.rs
trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs

parser/lexer: add support for goto statements

---

trunk_lexer/src/lexer.rs

Now span refers to the start of a token and position is tracked inside the `next` method.

lexer: re-work position tracking

---

trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs

parser: support nullsafe method calls

---

trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs
trunk_parser/src/parser/vars.rs

parser: support variable variables

---

trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs

parser: support unpacking array items

---

trunk_lexer/src/lexer.rs
trunk_lexer/src/token.rs
trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs

parser: support all unary ops

---

trunk_lexer/src/lexer.rs
trunk_lexer/src/token.rs
trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs
trunk_parser/src/parser/precedence.rs

parser: support rest of infix ops

---

trunk_lexer/src/lexer.rs
trunk_lexer/src/token.rs
trunk_parser/src/ast.rs
trunk_parser/src/parser/mod.rs

parser: support empty yield expressions

---

trunk_lexer/src/lexer.rs
trunk_parser/src/parser/mod.rs

```php
if (true):
echo "Hi!";
endif;
```

parser: support shorthand if statements

---

trunk_lexer/src/lexer.rs
trunk_parser/src/parser/mod.rs

parser: support short foreach statement

---

trunk_lexer/src/lexer.rs

Fixes #37.
In addition, fixes a case not handled correctly by the old code: `1_` should produce an integer `1` and an identifier `_`, but previously would've been treated as a single integer token.
One limitation of this implementation is that `i128` is used for integers that overflow to float. It allows us to handle all numeric bases, but panics are still possible with very large literals. Rust doesn't have a `from_str_radix` method for floats.

Lexer: handle all types of numeric literals

---

trunk_lexer/src/lexer.rs

Handle uppercase letters for int literals

---

trunk_lexer/src/lexer.rs
trunk_parser/src/parser/mod.rs

parser: support missing shorthand statements

---

trunk_parser/src/parser/mod.rs

parser: only allow certain statements at top level

---

src/ast.rs
src/parser/mod.rs

parser: add support for group use statements

---

src/ast.rs
src/lexer/lexer.rs
src/parser/mod.rs

parser: add support for trait adaptations

---

.github/workflows/third-party-tests.yml
tests/third_party_tests.rs

build failure is expected, and we can consider this parser to be ready to start using once it doesn't fail anymore :)

chore: test against third party libraries

---

src/parser/internal/namespace.rs
tests/0158/ast.txt

fix: make sure unbraced namespaces don't get nested

---

src/lexer/mod.rs
src/lexer/token.rs
src/parser/internal/functions.rs
src/parser/mod.rs

Signed-off-by: azjezz <azjezz@protonmail.com>

fix: formatting

---

src/lexer/mod.rs
src/lexer/state.rs
src/parser/state.rs

chore: small perf improvements for the lexer

---

src/lexer/byte_string.rs
src/parser/internal/classish.rs
src/parser/internal/classish_statements.rs
src/parser/internal/functions.rs
src/parser/internal/identifiers.rs
src/parser/internal/mod.rs
src/parser/internal/punctuations.rs
src/parser/internal/tokens.rs
src/parser/internal/types.rs
src/parser/macros.rs
src/parser/mod.rs
src/parser/state.rs

before ( https://github.com/php-rust-tools/parser/actions/runs/3629643352/jobs/6122090263 )
```
Time (mean ± σ):      2.900 s ±  0.061 s    [User: 2.777 s, System: 0.245 s]
Range (min … max):    2.797 s …  2.997 s    10 runs
```
after ( https://github.com/php-rust-tools/parser/actions/runs/3629727159/jobs/6122269847 )
```
Time (mean ± σ):      2.199 s ±  0.009 s    [User: 2.121 s, System: 0.167 s]
Range (min … max):    2.189 s …  2.212 s    10 runs
```

chore: avoid cloning tokens

---

src/lexer/mod.rs
src/parser/internal/blocks.rs
src/parser/internal/punctuations.rs
src/parser/mod.rs

feature: allow opening / closing tags in middle of scripting code

---

src/parser/internal/data_type.rs
src/parser/internal/modifiers.rs
src/parser/internal/precedences.rs
src/parser/internal/try_block.rs

all inlined functions here have only 1 call site.

chore: inline some functions

---

.github/workflows/third-party-tests.yml
tests/third_party_tests.rs

@azjezz PR based on your link within the tweet https://twitter.com/azjezz/status/1600960177179873280. Hopefully I have done this correctly

add-chubbyphp-framework

---

.github/workflows/third-party-tests.yml
tests/third_party_tests.rs

See: #178 (https://github.com/php-rust-tools/parser/pull/178#discussion_r1044242481)

chore: add silverstripe framework to integration tests

---

.github/workflows/third-party-tests.yml
tests/third_party_tests.rs

chore: add more third party projects

---

src/parser/internal/enums.rs
tests/fixtures/0301-enum-call/ast.txt
tests/fixtures/0301-enum-call/parser-error.txt
tests/fixtures/0302-enum-call-static/ast.txt
tests/fixtures/0302-enum-call-static/parser-error.txt
tests/fixtures/0303-enum-invoke/ast.txt
tests/fixtures/0303-enum-invoke/parser-error.txt
tests/fixtures/0308-enum-clone/code.php
tests/fixtures/0308-enum-clone/parser-error.txt
tests/fixtures/0309-enum-debug-info/code.php
tests/fixtures/0309-enum-debug-info/parser-error.txt
tests/fixtures/0310-enum-isset/code.php
tests/fixtures/0310-enum-isset/parser-error.txt
tests/fixtures/0311-enum-set-state/code.php
tests/fixtures/0311-enum-set-state/parser-error.txt
tests/fixtures/0312-enum-tostring/code.php
tests/fixtures/0312-enum-tostring/parser-error.txt
tests/fixtures/0313-enum-unset/code.php
tests/fixtures/0313-enum-unset/parser-error.txt
tests/fixtures/0314-php-issue-10083/ast.txt
tests/fixtures/0314-php-issue-10083/code.php

chore: update list of forbidden methods on enum

---

schema.json
src/parser/ast/mod.rs
src/parser/expressions.rs
tests/fixtures/0090/ast.txt
tests/fixtures/0098/ast.txt
tests/fixtures/0099/ast.txt
tests/fixtures/0100/ast.txt
tests/fixtures/0271/ast.txt
tests/fixtures/0273/ast.txt
tests/fixtures/0274/ast.txt
tests/fixtures/0275/ast.txt
tests/fixtures/0282-dynamic-variable/ast.txt
tests/fixtures/0284/ast.txt
tests/fixtures/0285-reserved-type-name/ast.txt
tests/fixtures/0292-reserved-const/ast.txt
tests/fixtures/0319/ast.txt

RFC: https://wiki.php.net/rfc/dynamic_class_constant_fetch

feat: support PHP 8.3 dynamic constant fetch

---

src/parser/error.rs
src/parser/internal/arrays.rs
src/parser/internal/data_type.rs
src/parser/internal/enums.rs
src/parser/internal/identifiers.rs
src/parser/internal/modifiers.rs
src/parser/internal/properties.rs
src/parser/mod.rs
src/parser/state/mod.rs
tests/fixtures/0086/error.txt
tests/fixtures/0112/error.txt
tests/fixtures/0128/error.txt
tests/fixtures/0129/error.txt
tests/fixtures/0152/error.txt
tests/fixtures/0328-multiple-errors/code.php
tests/fixtures/0328-multiple-errors/error.txt

feat: make the parser fault tolerant

---

schema.json
src/parser/ast/control_flow.rs
src/parser/ast/loops.rs
src/parser/ast/mod.rs
src/parser/ast/utils.rs
src/parser/internal/blocks.rs
src/parser/internal/control_flow.rs
src/parser/internal/loops.rs
src/parser/internal/utils.rs

chore: remove utility nodes
